title: Gorbin Mathew
logo: https://github.com/GorbinMathew/Portfolio/blob/a41c90ce21cdd9e841d179de321efd1d5b49fa85/MI%203.png
description: Technical Writer
show_downloads: False
theme: jekyll-theme-minimal
